spring.application.name: client-registration

spring.jpa.hibernate.ddl-auto: none
spring.h2.console.enabled: true

spring.datasource.jdbc-url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
springspring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect